-- Insert Users
INSERT INTO USERS (FIRST_NAME, FULL_NAME, CREATED_DATE, UPDATED_DATE)
VALUES ('Earl', 'Omictin', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Insert Categories
INSERT INTO CATEGORY (NAME, CREATED_DATE, UPDATED_DATE)
VALUES
('Salary', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('Food', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('Travel', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('Rent', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());